In [10]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import pprint as pprint

from nba_api.stats.static import teams
from nba_api.stats.endpoints import leaguegamefinder

#api_key = "d1b1f11391mshdfeb577395264e5p18b5d8jsn5ad94c991841"
#url = "https://api-nba-v1.p.rapidapi.com/games/seasonYear/2017"

# Output File (CSV)
nba_file = pd.read_csv('2017_nba_season_stats.csv')
nba_file.head()

,Year,Player,Pos,Age,Tm,G,GS,PTS,Minutes Played,PER,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS.1
0,2017,Alex Abrines,SG,23,OKC,68,6,406,1055,10.1,...,0.898,18,68,86,40,37,8,33,114,406
1,2017,Quincy Acy,PF,26,TOT,38,1,222,558,11.8,...,0.750,20,95,115,18,14,15,21,67,222
2,2017,Quincy Acy,PF,26,DAL,6,0,13,48,-1.4,...,0.667,2,6,8,0,0,0,2,9,13
3,2017,Quincy Acy,PF,26,BRK,32,1,209,510,13.1,...,0.754,18,89,107,18,14,15,19,58,209
4,2017,Steven Adams,C,23,OKC,80,80,905,2389,16.5,...,0.611,282,333,615,86,88,78,146,195,905

In [11]:
nba_teams = teams.get_teams()
# Select the dictionary for the Celtics, which contains their team ID
celtics = [team for team in nba_teams if team['abbreviation'] == 'BOS'][0]
celtics_id = celtics['id']

In [12]:
# Query for games where the Celtics were playing
gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=celtics_id)
# The first DataFrame of those returned is what we want.
games = gamefinder.get_data_frames()[0]
games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22019,1610612738,BOS,Boston Celtics,1521900074,2019-07-13,BOS vs. MEM,L,201,88,...,0.792,13,30,43,12,7,4,14,26,-6.8
1,22019,1610612738,BOS,Boston Celtics,1521900064,2019-07-11,BOS @ MEM,W,199,113,...,0.731,16,41,57,24,4,6,17,28,21.0
2,22019,1610612738,BOS,Boston Celtics,1521900045,2019-07-09,BOS vs. DEN,W,200,95,...,0.652,11,28,39,21,10,2,13,22,1.4
3,22019,1610612738,BOS,Boston Celtics,1521900035,2019-07-08,BOS vs. CLE,None,13,2,...,NaN,2,6,8,0,1,0,3,2,0.0
4,22019,1610612738,BOS,Boston Celtics,1521900035,2019-07-08,BOS vs. CLE,W,187,87,...,0.900,11,25,36,23,13,8,14,15,17.8